### ISSUE TITLE
Unable to install for Python 3

### ISSUE THREAD

**Issue by LockStoch** [rembish/colorprint#2]
Having trouble installing the package. I get the following error using `pip install colorprint`

```
Collecting colorprint
  Using cached colorprint-0.1.tar.gz (2.1 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/username/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7f/w4ftkq_j4p140_hpzq2t3y1c0000gn/T/pip-install-zub6ghtb/colorprint/setup.py'"'"'; __file__='"'"'/private/var/folders/7f/w4ftkq_j4p140_hpzq2t3y1c0000gn/T/pip-install-zub6ghtb/colorprint/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/7f/w4ftkq_j4p140_hpzq2t3y1c0000gn/T/pip-install-zub6ghtb/colorprint/pip-egg-info
         cwd: /private/var/folders/7f/w4ftkq_j4p140_hpzq2t3y1c0000gn/T/pip-install-zub6ghtb/colorprint/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7f/w4ftkq_j4p140_hpzq2t3y1c0000gn/T/pip-install-zub6ghtb/colorprint/setup.py", line 3, in <module>
        import colorprint
      File "/private/var/folders/7f/w4ftkq_j4p140_hpzq2t3y1c0000gn/T/pip-install-zub6ghtb/colorprint/colorprint.py", line 32, in <module>
        import __builtin__
    ModuleNotFoundError: No module named '__builtin__'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Also tried to install on a fresh conda virtual environment but got the same error.

**Comment by LockStoch** [comment]
Oh sorry, I see this is a known issue #1. I did not realise Python 3 support was not yet implemented. I will close this issue.
